
atmosphere-grid:
  number-of-layers: 50
  
planet:
  planet-mass: 4.132740164511634e+27
  planet-radius: 586785200.0
  surface-albedo: 0.1
  number-of-zenith-angles: 4
  photon-scale-factor: 1.0

optical-properties:
  ir:
    k-method: RandomOverlapResortRebin
    opacities: {k-distributions: true, CIA: true, rayleigh: true, photolysis-xs: true,
      water-continuum: MT_CKD}
  solar:
    k-method: RandomOverlapResortRebin
    opacities: {k-distributions: true, CIA: true, rayleigh: true, photolysis-xs: true,
      water-continuum: MT_CKD}
