
atmosphere-grid:
  bottom: 0.0 # cm
  top: atmospherefile # cm
  number-of-layers: 100

planet:
  planet-mass: 4.132740e+27 # 0.692x Earth mass (grams) Agol et al. (2021)
  planet-radius: 5.867852e+08 # 0.920x Earth Radius (cm) Agol et al. (2021)
  surface-albedo: 0.1
  solar-zenith-angle: 60.0 # degrees
  # S1 is the XUV flux relative to Earth. The choice below
  # is based on Van Looveren et al. (2024), Sec. 3.2
  hydrogen-escape: {type: zahnle, S1: 300}
  water: {fix-water-in-troposphere: off, gas-rainout: off, water-condensation: off}

particles:
- {name: H2Oaer, RH-condensation: 0.5}

boundary-conditions:
# Follows Ranjan et al. (2023), ApJ
- name: O
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: O3
  lower-boundary: {type: vdep, vdep: 0.4}
  upper-boundary: {type: veff, veff: 0.0}
- name: OH
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: HO2
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2O2
  lower-boundary: {type: vdep, vdep: 0.5}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2CO
  lower-boundary: {type: vdep, vdep: 0.1}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCO
  lower-boundary: {type: vdep, vdep: 0.1}
  upper-boundary: {type: veff, veff: 0.0}
- name: CH3O
  lower-boundary: {type: vdep, vdep: 0.1}
  upper-boundary: {type: veff, veff: 0.0}
- name: C2H6
  lower-boundary: {type: vdep, vdep: 1.0e-5}
  upper-boundary: {type: veff, veff: 0.0}
- name: NH3
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: NO
  lower-boundary: {type: vdep, vdep: 0.02}
  upper-boundary: {type: veff, veff: 0.0}
- name: NO2
  lower-boundary: {type: vdep, vdep: 0.02}
  upper-boundary: {type: veff, veff: 0.0}
- name: NO3
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: HNO2
  lower-boundary: {type: vdep, vdep: 0.5}
  upper-boundary: {type: veff, veff: 0.0}
- name: HNO3
  lower-boundary: {type: vdep, vdep: 4.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCN
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}
- name: CN
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}

# Assumed to be the same as HCN
- name: HCCCN
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}